sonar.projectName=EcoTrack
sonar.organization=oussamaredd
sonar.projectKey=Oussamaredd_EcoTrack
sonar.sourceEncoding=UTF-8
sonar.sources=app/src,api/src,database
sonar.tests=app/src/tests,api/src/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,app/src/tests/**,api/src/tests/**
sonar.test.inclusions=app/src/tests/**,api/src/tests/**
sonar.typescript.tsconfigPaths=app/tsconfig.json,api/tsconfig.json,database/tsconfig.json
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info,api/coverage/lcov.info
sonar.coverage.exclusions=database/**,app/src/hooks/useApiReady.ts,app/src/pages/auth/LoginPage.tsx,app/src/services/api.tsx,app/src/hooks/useAuth.tsx,app/src/components/AppStatusScreen.tsx,app/src/routes/AppRouter.tsx,app/src/pages/landing/LandingPage.tsx,app/src/routes/guards/RequireAuth.tsx,app/src/routes/guards/RequireGuest.tsx,app/src/components/LoginButton.tsx,app/src/components/admin/SystemSettings.tsx,api/src/modules/users/users.repository.ts,api/src/modules/users/users.service.ts,api/src/modules/users/users.contract.ts,api/src/modules/admin/admin.settings.repository.ts,api/src/modules/auth/auth.service.ts
