sonar.projectName=EcoTrack
sonar.organization=oussamaredd
sonar.projectKey=Oussamaredd_EcoTrack
sonar.sourceEncoding=UTF-8
sonar.sources=app/src,api/src,database
sonar.tests=app/src/tests,api/src/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,app/src/tests/**,api/src/tests/**
sonar.test.inclusions=app/src/tests/**,api/src/tests/**
sonar.typescript.tsconfigPaths=app/tsconfig.json,api/tsconfig.json,database/tsconfig.json
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info,api/coverage/lcov.info
