import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

import type { ReportExport } from 'ecotrack-database';

import { decodeStoredReportContent, resolveReportDownloadMeta } from './report-artifact.utils.js';

export const REPORT_STATUS_GENERATED = 'generated';
export const REPORT_STATUS_EMAIL_DELIVERED = 'email_delivered';
export const REPORT_STATUS_EMAIL_DELIVERY_FAILED = 'email_delivery_failed';

export type ReportDeliveryResult = {
  channel: 'filesystem_outbox';
  deliveredAt: string;
  outboxPath: string;
  recipient: string;
  status: 'delivered';
};

type DeliverableReport = Pick<
  ReportExport,
  'id' | 'periodStart' | 'periodEnd' | 'selectedKpis' | 'format' | 'emailTo' | 'fileContent' | 'createdAt'
>;

const DEFAULT_REPORT_OUTBOX_DIRECTORY = join('.runtime', 'report-outbox');
const MIME_BOUNDARY = `ecotrack-report-boundary-${Date.now().toString(36)}`;
const EOL = '\r\n';

const formatDateOnly = (value: Date) => value.toISOString().slice(0, 10);

const toAttachmentFileName = (reportId: string, extension: string) => `report-${reportId}.${extension}`;

const normalizeFileToken = (value: string) => value.replace(/[^a-z0-9-]+/gi, '-').replace(/-+/g, '-');

export const resolveReportOutboxDirectory = (baseDirectory = process.cwd()) =>
  resolve(baseDirectory, DEFAULT_REPORT_OUTBOX_DIRECTORY);

const buildReportSummary = (report: DeliverableReport, deliveredAt: string) =>
  [
    'EcoTrack monthly operational report delivery',
    '',
    `Report ID: ${report.id}`,
    `Generated At: ${new Date(report.createdAt).toISOString()}`,
    `Delivered At: ${deliveredAt}`,
    `Period Start: ${new Date(report.periodStart).toISOString()}`,
    `Period End: ${new Date(report.periodEnd).toISOString()}`,
    `Selected KPIs: ${report.selectedKpis.join(', ') || 'none'}`,
    '',
    'This message was generated by the EcoTrack manager reporting workflow.',
    'The attached export is stored in the local development outbox.',
  ].join(EOL);

const buildEmailMessage = (report: DeliverableReport, deliveredAt: string) => {
  const metadata = resolveReportDownloadMeta(report.format);
  const attachmentName = toAttachmentFileName(report.id, metadata.fileExtension);
  const attachmentBase64 = decodeStoredReportContent(report.fileContent).toString('base64');
  const normalizedRecipient = report.emailTo?.trim().toLowerCase();

  if (!normalizedRecipient) {
    throw new Error('Cannot deliver report email without a recipient address.');
  }

  const periodLabel = `${formatDateOnly(new Date(report.periodStart))} to ${formatDateOnly(new Date(report.periodEnd))}`;
  const body = buildReportSummary(report, deliveredAt);

  return [
    'From: EcoTrack Reports <noreply@ecotrack.local>',
    `To: ${normalizedRecipient}`,
    `Subject: EcoTrack monthly report (${periodLabel})`,
    'MIME-Version: 1.0',
    `Date: ${new Date(deliveredAt).toUTCString()}`,
    `Message-ID: <report-${report.id}@ecotrack.local>`,
    `Content-Type: multipart/mixed; boundary="${MIME_BOUNDARY}"`,
    '',
    `--${MIME_BOUNDARY}`,
    'Content-Type: text/plain; charset="utf-8"',
    'Content-Transfer-Encoding: 8bit',
    '',
    body,
    '',
    `--${MIME_BOUNDARY}`,
    `Content-Type: ${metadata.contentType}`,
    'Content-Transfer-Encoding: base64',
    `Content-Disposition: attachment; filename="${attachmentName}"`,
    '',
    attachmentBase64,
    '',
    `--${MIME_BOUNDARY}--`,
    '',
  ].join(EOL);
};

export const deliverReportByEmail = async (
  report: DeliverableReport,
  baseDirectory = process.cwd(),
): Promise<ReportDeliveryResult> => {
  const recipient = report.emailTo?.trim().toLowerCase();
  if (!recipient) {
    throw new Error('Cannot deliver report email without a recipient address.');
  }

  const outboxDirectory = resolveReportOutboxDirectory(baseDirectory);
  const deliveredAt = new Date().toISOString();
  const fileName = `${formatDateOnly(new Date(deliveredAt)).replace(/-/g, '')}-${normalizeFileToken(report.id)}.eml`;
  const outboxPath = join(outboxDirectory, fileName);

  await mkdir(outboxDirectory, { recursive: true });
  await writeFile(outboxPath, buildEmailMessage(report, deliveredAt), 'utf8');

  return {
    channel: 'filesystem_outbox',
    deliveredAt,
    outboxPath,
    recipient,
    status: 'delivered',
  };
};
