import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { deliverReportByEmail, resolveReportOutboxDirectory } from '../planning/report-delivery.utils.js';

describe('report delivery utils', () => {
  it('writes a MIME message with the report attachment into the development outbox', async () => {
    const tempRoot = await mkdtemp(join(process.cwd(), '.tmp-report-delivery-'));

    try {
      const result = await deliverReportByEmail(
        {
          id: '3b8c572a-1ff1-4d1b-90ce-f5d05ea0ef7f',
          periodStart: new Date('2026-02-01T00:00:00.000Z'),
          periodEnd: new Date('2026-02-28T23:59:59.000Z'),
          selectedKpis: ['tours', 'collections', 'anomalies'],
          format: 'pdf',
          emailTo: 'OPS@EXAMPLE.COM',
          fileContent: Buffer.from('%PDF-1.4\nmock content').toString('base64'),
          createdAt: new Date('2026-03-02T14:00:00.000Z'),
        },
        tempRoot,
      );

      expect(result.status).toBe('delivered');
      expect(result.recipient).toBe('ops@example.com');
      expect(result.outboxPath.startsWith(resolveReportOutboxDirectory(tempRoot))).toBe(true);

      const message = await readFile(result.outboxPath, 'utf8');
      expect(message).toContain('To: ops@example.com');
      expect(message).toContain('Content-Type: multipart/mixed;');
      expect(message).toContain('filename="report-3b8c572a-1ff1-4d1b-90ce-f5d05ea0ef7f.pdf"');
      expect(message).toContain('This message was generated by the EcoTrack manager reporting workflow.');
    } finally {
      await rm(tempRoot, { recursive: true, force: true });
    }
  });
});
